import path from 'node:path';

import YAML from 'yaml';

import type { HarnessPaths } from '../paths';
import { taskStateDir } from '../paths';
import { readAgentPrompt } from './load';
import type { AgentDefinition } from './schema';

/** POSIX single-quote escaping: the only form that is safe for arbitrary text. */
export function shQuote(value: string): string {
  return `'${value.split("'").join(String.raw`'\''`)}'`;
}

export function modelFor(agent: AgentDefinition, adapter: string, fallback = ''): string {
  return agent.model[adapter] ?? fallback;
}

/**
 * Compile a harness agent into a Claude Code subagent file. Agents are authored
 * once, in one vendor-neutral format; this is the projection onto `.claude/`.
 */
export function compileToClaudeMarkdown(paths: HarnessPaths, agent: AgentDefinition): string {
  const frontmatter = YAML.stringify({
    name: agent.name,
    description: agent.description,
    model: modelFor(agent, 'claude', 'inherit'),
    tools: agent.tools.join(', '),
  }).trimEnd();

  const body = readAgentPrompt(paths, agent).trimEnd();
  const scope =
    agent.writeScope.length > 0
      ? `\n\n## Write scope (enforced at handoff)\n\nYou may only create or modify files matching:\n${agent.writeScope
          .map((glob) => `- \`${glob}\``)
          .join('\n')}\n`
      : '\n';

  return `---\n${frontmatter}\n---\n\n${body}\n${scope}`;
}

export interface AgentEnvOptions {
  adapter: string;
  taskId: string;
  mode: 'headless' | 'interactive';
  /** Overrides the agent's declared model -- used by `--model` on the CLI. */
  model?: string;
}

/**
 * The handoff between the TypeScript and shell layers. TypeScript resolves
 * every value; the shell sources this file and never parses YAML itself.
 */
export function renderAgentEnv(
  paths: HarnessPaths,
  agent: AgentDefinition,
  options: AgentEnvOptions,
): string {
  const stateDir = taskStateDir(paths, options.taskId, agent.name);
  const vars: Record<string, string> = {
    HARNESS_ROOT: paths.root,
    HARNESS_DIR: paths.dir,
    HARNESS_TASK: options.taskId,
    HARNESS_AGENT: agent.name,
    HARNESS_AGENT_DESC: agent.description,
    HARNESS_ADAPTER: options.adapter,
    HARNESS_MODEL: options.model ?? modelFor(agent, options.adapter),
    HARNESS_EFFORT: agent.effort,
    HARNESS_TOOLS: agent.tools.join(','),
    // Space separated; the gate splits it with globbing disabled (`set -f`).
    HARNESS_WRITE_SCOPE: agent.writeScope.join(' '),
    HARNESS_HANDOFF_TO: agent.handoffTo ?? '',
    HARNESS_MODE: options.mode,
    HARNESS_STATE_DIR: stateDir,
    HARNESS_CONTEXT_FILE: path.join(stateDir, 'context.md'),
    HARNESS_OUTPUT_FILE: path.join(stateDir, 'output.md'),
    HARNESS_RESULT_FILE: path.join(stateDir, 'result.json'),
    HARNESS_TRANSCRIPT_FILE: path.join(stateDir, 'transcript.log'),
  };

  const lines = Object.entries(vars).map(([key, value]) => `${key}=${shQuote(value)}`);
  return `# generated by harness -- do not edit\n${lines.join('\n')}\nexport ${Object.keys(vars).join(' ')}\n`;
}
