#!/bin/sh
# One agent's turn on one task: render context, run the adapter, hand off.
#
# Usage: stage.sh --task <id> --agent <name> [--adapter <name>] [--mode headless|interactive]
#
# Exit: 0 handed off, 10 blocked by a gate, otherwise the adapter's own failure.
set -eu

_here=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
# shellcheck source=../lib/log.sh
. "$_here/lib/log.sh"
# shellcheck source=../lib/exec.sh
. "$_here/lib/exec.sh"

TASK=''; AGENT=''; ADAPTER=''; MODE=headless
while [ "$#" -gt 0 ]; do
  case $1 in
    --task)    TASK=${2:?--task needs a value}; shift 2 ;;
    --agent)   AGENT=${2:?--agent needs a value}; shift 2 ;;
    --adapter) ADAPTER=${2:?--adapter needs a value}; shift 2 ;;
    --mode)    MODE=${2:?--mode needs a value}; shift 2 ;;
    *) log_die 2 "unknown argument: $1" ;;
  esac
done
[ -n "$TASK" ]  || log_die 2 "stage.sh needs --task"
[ -n "$AGENT" ] || log_die 2 "stage.sh needs --agent"

# --- 1. render the agent's working set -------------------------------------
set -- ctx --task "$TASK" --agent "$AGENT" --mode "$MODE"
[ -n "$ADAPTER" ] && set -- "$@" --adapter "$ADAPTER"
state=$(harness_run "$@") || log_die 1 "could not render context for $AGENT"

# agent.env is generated by the CLI: every value already resolved and quoted,
# which is why nothing here has to understand YAML.
# shellcheck disable=SC1091
. "$state/agent.env"

# A stage starts from a clean slate so a stale reject or checklist from a
# previous attempt cannot leak into this handoff.
rm -f "$state/reject.txt" "$state/checklist.env" "$state/output.md"

# --- 2. run the adapter ----------------------------------------------------
adapter_script="$_here/adapters/$HARNESS_ADAPTER.sh"
[ -f "$adapter_script" ] || log_die 1 "no adapter script for '$HARNESS_ADAPTER' ($adapter_script)"

log_info "$AGENT ($HARNESS_ADAPTER/${HARNESS_MODEL:-default}) on $TASK"

set +e
sh "$adapter_script" >"$HARNESS_TRANSCRIPT_FILE" 2>&1
rc=$?
set -e

if [ "$rc" -ne 0 ]; then
  tail -n 40 "$HARNESS_TRANSCRIPT_FILE" >&2 || true
  log_die "$rc" "$AGENT failed (exit $rc) -- $TASK stays with $AGENT"
fi

# --- 3. hand off -----------------------------------------------------------
set -- handoff --task "$TASK" --agent "$AGENT"

if [ -s "$state/reject.txt" ]; then
  set -- "$@" --reject "$(cat "$state/reject.txt")"
fi

# checklist.env is `id=true` / `id=false`, one per line.
if [ -f "$state/checklist.env" ]; then
  while IFS= read -r entry; do
    [ -n "$entry" ] || continue
    case $entry in \#*) continue ;; esac
    set -- "$@" --checklist "$entry"
  done <"$state/checklist.env"
fi

harness_run "$@"
