import * as harness from "../../src/index.js";
import { HARNESS_DIRECTORY, harnessPackageMetadata } from "../../src/index.js";

/**
 * The published surface of the package. Listing it explicitly turns an
 * accidental removal or rename into a failing test rather than a silent
 * breaking change for consumers.
 */
const PUBLIC_API = [
  "BUILT_IN_AGENT_IDS",
  "CI_TEMPLATE_PATH",
  "CLI_COMMANDS",
  "CLI_EXIT_CODES",
  "DEFAULT_CHECK_TIMEOUT_MS",
  "DEFAULT_COMMAND_TIMEOUT_MS",
  "DEFAULT_KILL_GRACE_MS",
  "DEFAULT_KILL_SIGNAL",
  "DEFAULT_MAX_OUTPUT_BYTES",
  "DIAGNOSTIC_STATUSES",
  "EMPTY_COMMAND_OUTPUT",
  "ENVIRONMENT_ALLOWLIST",
  "EXECUTABLE_MODE",
  "EXISTING_HOOK_POLICIES",
  "HARNESS_DIRECTORY",
  "HARNESS_ERROR_KINDS",
  "HARNESS_GIT_HOOKS_PATH",
  "HARNESS_PACKAGE_NAME",
  "HARNESS_PATHS",
  "HOOKS_PATH_SCOPES",
  "HOOK_NAMES",
  "HOOK_RUNNERS",
  "HarnessError",
  "INSTALL_ACTIONS",
  "INSTALL_MANIFEST_VERSION",
  "LAUNCHER_PATH",
  "LOCKFILE_PACKAGE_MANAGERS",
  "MANAGED_FILE_KINDS",
  "MAX_CHECK_TIMEOUT_MS",
  "MIN_CHECK_TIMEOUT_MS",
  "MISSING_SCRIPT_BEHAVIOURS",
  "MODEL_PROFILES",
  "NODE_COMMAND_RUNNER_DEFAULTS",
  "PACKAGE_MANAGERS",
  "PHASES",
  "PROJECT_SCRIPT_NAMES",
  "PackageManagerAmbiguityError",
  "REQUIRED_NODE_VERSION",
  "REQUIRED_TOOLS",
  "RULE_ORIGIN_PRECEDENCE",
  "RULE_SET_HASH_VERSION",
  "RUNTIME_INSTALL_ARGV",
  "RUNTIME_INSTALL_TIMEOUT_MS",
  "RUNTIME_PACKAGE_NAME",
  "RuleResolutionError",
  "RuleValidationError",
  "SEEDED_TEMPLATE_PATHS",
  "SEVERITIES",
  "VALIDATION_MODES",
  "WORKFLOW_DIRECTORY",
  "agentDefinitionSchema",
  "agentIdSchema",
  "agentToolsSchema",
  "buildChildEnvironment",
  "buildHarnessLauncher",
  "buildHookDispatcher",
  "buildPackageManagerCommand",
  "buildRuntimePackageManifest",
  "canonicalRule",
  "canonicalRuleSet",
  "canonicalStringify",
  "checkSchema",
  "commandSucceeded",
  "compareCodeUnits",
  "compileAgentPolicy",
  "createDefaultCliCommands",
  "createDefaultReportId",
  "createDeterministicReportId",
  "createNodeCommandRunner",
  "describeCommand",
  "describeCommandResult",
  "describeFailure",
  "detectLockfilePackageManagers",
  "diagnoseHarness",
  "discoverHookEnvironment",
  "discoverProjectProfile",
  "escapeForDoubleQuotes",
  "existingHookPolicySchema",
  "exitCodeForHarnessError",
  "formatDiagnosis",
  "formatInstallResult",
  "formatPhaseGateReport",
  "formatRuleIssue",
  "formatRuleIssues",
  "formatRuleSetExplanation",
  "formatRuleSetSummary",
  "harnessPackageMetadata",
  "harnessPath",
  "harnessReleaseTarballUrl",
  "harnessTemplateRoot",
  "hashManagedFile",
  "hashRuleSet",
  "hookRecordSchema",
  "hookScriptPath",
  "hooksConfigSchema",
  "installHarness",
  "installManifestSchema",
  "installRuntimeDependencies",
  "isBuiltInAgentId",
  "isSeededTemplate",
  "killProcessTree",
  "listHarnessTemplateFiles",
  "loadAgentDefinition",
  "loadHarnessRuleSet",
  "loadHooksConfig",
  "loadProjectConfig",
  "loadRuleBundle",
  "loadRuleDirectory",
  "loadYamlConfig",
  "managedFileEntrySchema",
  "managedFileKindSchema",
  "managedHookSchema",
  "mapBuiltInAgents",
  "modelProfileSchema",
  "nodeCommandRunner",
  "normalizeText",
  "packageManagerSchema",
  "parseCliArguments",
  "parseDeclaredPackageManager",
  "planHooks",
  "planInstallation",
  "portableProjectProfileSchema",
  "projectConfigSchema",
  "projectProfileSchema",
  "readHarnessTemplateFile",
  "readInstallManifest",
  "readPackageRepository",
  "readPackageVersion",
  "readTextFileIfPresent",
  "resolvePackageManager",
  "resolveProjectRoot",
  "resolveProjectScript",
  "resolveRuleSet",
  "ruleBundleSchema",
  "ruleSchema",
  "runCli",
  "runPhaseGates",
  "toPlannedFileSource",
  "toPortableProjectProfile",
  "toProjectPath",
  "toSpawnFailure",
  "versionOrder",
  "writeFileAtomic",
  "writeInstallManifest",
] as const;

describe("package metadata", () => {
  it("reserves .harness as the project-local installation directory", () => {
    expect(HARNESS_DIRECTORY).toBe(".harness");
    expect(harnessPackageMetadata).toEqual({
      directory: ".harness",
      name: "agentic-harness",
    });
  });
});

describe("public API surface", () => {
  it("exports exactly the documented bindings", () => {
    expect(Object.keys(harness).sort()).toEqual([...PUBLIC_API]);
  });

  it("resolves every exported binding to a defined value", () => {
    const surface: Record<string, unknown> = harness;

    expect(PUBLIC_API.length).toBeGreaterThan(0);

    for (const name of PUBLIC_API) {
      expect(surface[name]).toBeDefined();
    }
  });
});
